---

- name: Map the known eth0 Mac-addresses to the arp results
  shell: "arp -na | grep '{{ item.mac_address }}' | grep -Eo '[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}'"
  register: mapping_result
  ignore_errors: true
  loop: "{{ mac_address_mapping }}"
  changed_when: false

...
