---

# Get MAC address of the wlan interface
# Get MAC address of the ethernet interface
# Perform as root => "become: yes":
# shell: "ifconfig wlan0 | grep 'ether' | awk '{print $2}'"
# Perform as non-root => "become: no":
# shell: "/sbin/ifconfig wlan0 | grep 'ether' | awk '{print $2}'"

- name: Get MAC address from the wlan0 interface
  shell: "/sbin/ifconfig wlan0 | grep 'ether' | awk '{print $2}'"
  register: mac_address_wlan0
  changed_when: false
  when: debug

- name: Display MAC address of wlan0
  debug:
    msg: "MAC address of wlan0: {{ mac_address_wlan0.stdout }}"
  when: debug

...
