---

# Remove iptables rules for forwarding from eth0 to wlan0 and back
# 'sudo iptables -vS' displays the iptables rules
#
# iptables -D FORWARD -i eth0 -o wlan0 -j ACCEPT
# iptables -D FORWARD -i wlan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
# iptables -t nat -D POSTROUTING -o wlan0 -j MASQUERADE

- name: Remove iptables rule for forwarding eth0 to wlan0
  command: iptables -D FORWARD -i eth0 -o wlan0 -j ACCEPT

- name: Remove iptables rule for forwarding wlan0 to eth0
  command: iptables -D FORWARD -i wlan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT

- name: Remove POSTROUTING & MASQUERADE wlan0 from nat table
  command: iptables -t nat -D POSTROUTING -o wlan0 -j MASQUERADE

...
