---

# Display the content of the file '/boot/meta-data'

- name: Read meta-data file
  command: cat /boot/meta-data
  register: meta_data_file
  when:
    - debug
  changed_when: false

- name: Display meta-data file
  debug:
    msg: "{{ meta_data_file.stdout_lines }}"
  when:
    - debug

...
